name = 'Eclipse RP'
debug = true
port = 7788
players = 128
# password = 'ultra-password'
announce = false
# token = 'YOUR_TOKEN'
gamemode = 'Freeroam'
website = 'example.com'
language = 'en'
description = 'Eclipse rp №1'
modules = ['csharp-module', 'js-module', 'js-bytecode-module']
resources = ['chat', 'EclipseServer', 'EclipseClient']